// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/05478eb92a04b36ea25246d0806b4ff2fd04b415/ngstorage/index.d.ts
declare module 'ngstorage' {

    interface IStorageService {
        $default(items: {}): IStorageService;
        $reset(items?: {}): IStorageService;
        $apply(): void;
        $sync(): void;
        get<T>(key: string): T;
    }

    interface IStorageProvider extends angular.IServiceProvider {

        get<T>(key: string): T;
        set<T>(key: string, value: T): T;

        setKeyPrefix(prefix: string): void;
        setSerializer(serializer: (value: any) => string): void;
        setDeserializer(deserializer: (value: string) => any): void;
    }
}
